#!/usr/bin/env python
"""
Generate run-local Markdown documentation from an assembled benchmark HDF5.

``SUMMARY.md`` and ``EVAL_REPORT.md`` are written beside the assembled HDF5 so
the product, its configuration summary, and its automatic quality report stay
together. Generated files are refreshed on later assemblies, while hand-edited
files are preserved unless ``--overwrite`` is requested.

Usage:
    python src/run_documents.py OUT/o2band_benchmark.h5
    python src/run_documents.py OUT/o2band_benchmark.h5 --overwrite
"""

import argparse
import json
import os
import sys

import h5py
import numpy as np


SUMMARY_NAME = 'SUMMARY.md'
REPORT_NAME = 'EVAL_REPORT.md'
GENERATED_MARKER = '<!-- generated by src/run_documents.py; safe to replace -->'


def _decode(value):
    if isinstance(value, bytes):
        value = value.decode()
    if isinstance(value, str):
        try:
            return json.loads(value)
        except (TypeError, ValueError):
            return value
    if isinstance(value, np.generic):
        return value.item()
    return value


def _fmt(value):
    value = _decode(value)
    if isinstance(value, float):
        return '%.6g' % value
    if isinstance(value, (list, tuple)):
        return ', '.join(_fmt(v) for v in value)
    return str(value)


def _bands(h5):
    if 'reflectance' in h5:
        name = _decode(h5.attrs.get('band', os.path.basename(h5.filename)))
        yield str(name), h5
        return
    for name, group in h5.items():
        if isinstance(group, h5py.Group) and 'reflectance' in group:
            yield name, group


def _snapshot(h5_path, ref_floor):
    with h5py.File(h5_path, 'r') as h5:
        attrs = h5['metadata'].attrs if 'metadata' in h5 else h5.attrs
        metadata = {key: _decode(value) for key, value in attrs.items()}
        bands = []
        noise = []
        for name, group in _bands(h5):
            wvl = group['wvl'][:]
            sza = group['sza'][:]
            albedo = group['albedo'][:]
            reflectance = group['reflectance'][:]
            stderr = group['reflectance_stderr'][:]
            optical = group['optical_thickness']
            o2 = optical['o2_column'][:]
            h2o = optical['h2o_column'][:]
            rayleigh = optical['rayleigh_column'][:]
            bands.append({
                'name': name,
                'wvl_min': float(wvl[0]),
                'wvl_max': float(wvl[-1]),
                'n_wvl': int(wvl.size),
                'n_sza': int(sza.size),
                'n_albedo': int(albedo.size),
                'rho_min': float(np.nanmin(reflectance)),
                'rho_max': float(np.nanmax(reflectance)),
                'o2_max': float(np.nanmax(o2)),
                'h2o_max': float(np.nanmax(h2o)),
                'rayleigh_mean': float(np.nanmean(rayleigh)),
            })
            for i, angle in enumerate(sza):
                for j, alb in enumerate(albedo):
                    rho = reflectance[i, j]
                    err = stderr[i, j]
                    finite = np.isfinite(rho) & np.isfinite(err)
                    signal = finite & (rho > ref_floor)
                    relative = err[signal] / rho[signal]
                    noise.append({
                        'band': name,
                        'sza': float(angle),
                        'albedo': float(alb),
                        'n_signal': int(signal.sum()),
                        'rel_median': (float(np.median(relative))
                                       if relative.size else np.nan),
                        'rel_p95': (float(np.percentile(relative, 95))
                                    if relative.size else np.nan),
                        'rel_max': (float(np.max(relative))
                                    if relative.size else np.nan),
                        'abs_max': (float(np.max(err[finite]))
                                    if finite.any() else np.nan),
                    })
    return metadata, bands, noise


def _summary_markdown(h5_path, metadata, bands):
    keys = (
        ('Wavelength convention', 'wavelength_convention'),
        ('Spectral sampling', 'spectral_sampling'),
        ('Grid spacing (nm)', 'dwvl_nm'),
        ('Top altitude (km)', 'z_top_km'),
        ('Photons per g-point', 'photons_per_g_effective'),
        ('Independent MC runs', 'Nrun'),
        ('Line-wing cutoff (cm⁻¹)', 'wing_cutoff_cm'),
        ('O₂ CIA', 'o2_cia'),
        ('RT solver', 'solver'),
        ('Git commit', 'git_commit'),
    )
    lines = [
        '# O2 A/B-band RT benchmark — run summary',
        '',
        GENERATED_MARKER,
        '',
        'Automatically generated from `%s`. This file is stored with the run so '
        'its summary cannot drift away from the product.' % os.path.basename(h5_path),
        '',
        '## Configuration',
        '',
        '| Setting | Value |',
        '|---|---|',
    ]
    for label, key in keys:
        if key in metadata:
            lines.append('| %s | %s |' % (label, _fmt(metadata[key]).replace('|', r'\|')))
    lines += [
        '',
        '## Product contents',
        '',
        '| Band | Wavelength range (nm) | Points | Geometries | Reflectance range | '
        'O₂ OD max | H₂O OD max | Rayleigh OD mean |',
        '|---|---:|---:|---:|---:|---:|---:|---:|',
    ]
    for band in bands:
        lines.append(
            '| {name} | {wvl_min:.3f}–{wvl_max:.3f} | {n_wvl} | '
            '{n_sza} SZA × {n_albedo} albedo | {rho_min:.4g}–{rho_max:.4g} | '
            '{o2_max:.4g} | {h2o_max:.4g} | {rayleigh_mean:.4g} |'.format(**band))
    lines += [
        '',
        'The assembled HDF5 remains the authoritative source for datasets and '
        'metadata.',
        '',
    ]
    return '\n'.join(lines)


def _report_markdown(h5_path, noise, ref_floor, threshold):
    finite_p95 = [row['rel_p95'] for row in noise if np.isfinite(row['rel_p95'])]
    worst = max(finite_p95) if finite_p95 else np.nan
    passed = bool(finite_p95) and worst <= threshold
    lines = [
        '# EVAL_REPORT.md — automatic run-quality report',
        '',
        GENERATED_MARKER,
        '',
        'Automatically generated from `%s`.' % os.path.basename(h5_path),
        '',
        'This report covers checks computable from the assembled product. It does '
        'not replace independent HAPI, ABSCO, libRadtran, or participant comparisons.',
        '',
        '## Monte-Carlo noise',
        '',
        'Relative noise is `reflectance_stderr / reflectance` where reflectance '
        '> %.1e. The p95 threshold is %.4g.' % (ref_floor, threshold),
        '',
        '| Band | SZA | Albedo | Signal points | Relative median | Relative p95 | '
        'Relative max | Absolute stderr max |',
        '|---|---:|---:|---:|---:|---:|---:|---:|',
    ]
    for row in noise:
        lines.append(
            '| {band} | {sza:.1f} | {albedo:.2f} | {n_signal} | '
            '{rel_median:.4g} | {rel_p95:.4g} | {rel_max:.4g} | '
            '{abs_max:.4g} |'.format(**row))
    result = 'PASS' if passed else 'FAIL'
    lines += [
        '',
        '**Worst relative-stderr p95:** %.4g — **%s** against threshold %.4g.'
        % (worst, result, threshold),
        '',
    ]
    return '\n'.join(lines)


def _atomic_write(path, content):
    tmp = '%s.%d.tmp' % (path, os.getpid())
    with open(tmp, 'w') as stream:
        stream.write(content)
    os.replace(tmp, path)


def _generated_file(path):
    if not os.path.isfile(path):
        return False
    try:
        with open(path) as stream:
            return GENERATED_MARKER in stream.read(512)
    except OSError:
        return False


def save_run_documents(h5_path, output_dir=None, overwrite=False,
                       ref_floor=1.0e-3, noise_threshold=0.01):
    """Write SUMMARY.md and EVAL_REPORT.md beside ``h5_path``.

    Returns ``{name: {'path': path, 'status': 'written'|'preserved'}}``.
    """
    h5_path = os.path.abspath(h5_path)
    if not os.path.isfile(h5_path):
        raise OSError('assembled HDF5 does not exist: %s' % h5_path)
    output_dir = os.path.abspath(output_dir or os.path.dirname(h5_path))
    os.makedirs(output_dir, exist_ok=True)
    paths = {
        SUMMARY_NAME: os.path.join(output_dir, SUMMARY_NAME),
        REPORT_NAME: os.path.join(output_dir, REPORT_NAME),
    }
    # Rebuild our own generated files on every assembly, but never replace a
    # curated document merely because it has the same standard filename.
    pending = {name: path for name, path in paths.items()
               if overwrite or not os.path.exists(path) or _generated_file(path)}
    result = {
        name: {'path': path, 'status': ('written' if name in pending else 'preserved')}
        for name, path in paths.items()
    }
    if not pending:
        return result

    metadata, bands, noise = _snapshot(h5_path, ref_floor)
    content = {
        SUMMARY_NAME: _summary_markdown(h5_path, metadata, bands),
        REPORT_NAME: _report_markdown(
            h5_path, noise, ref_floor=ref_floor, threshold=noise_threshold),
    }
    for name, path in pending.items():
        _atomic_write(path, content[name])
    return result


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    parser.add_argument('h5', help='assembled benchmark or per-band HDF5')
    parser.add_argument('--overwrite', action='store_true',
                        help='replace existing SUMMARY.md/EVAL_REPORT.md')
    parser.add_argument('--ref-floor', type=float, default=1.0e-3)
    parser.add_argument('--noise-threshold', type=float, default=0.01)
    args = parser.parse_args(argv)
    try:
        result = save_run_documents(
            args.h5, overwrite=args.overwrite, ref_floor=args.ref_floor,
            noise_threshold=args.noise_threshold)
    except OSError as error:
        parser.error(str(error))
    for name in (SUMMARY_NAME, REPORT_NAME):
        item = result[name]
        print('%s %s: %s' % (item['status'], name, item['path']))
    return 0


if __name__ == '__main__':
    sys.exit(main())
